version: '3.7'

services:
    slim:
        build:
            context: .
            dockerfile: Dockerfile
        working_dir: /var/www
        command: php -S 0.0.0.0:8080 -t public
        environment:
            docker: "true"
            DB_HOST: db
            DB_DATABASE: course_marks_db
            DB_USERNAME: user
            DB_PASSWORD: password
        ports:
            - "8080:8080"
        volumes:
            - .:/var/www
            - logs:/var/www/logs
        depends_on:
            - db

    db:
        image: mysql:8.0
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: course_marks_db
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: rootpassword
        volumes:
            - db-data:/var/lib/mysql

volumes:
    logs:
        driver: local
    db-data:
        driver: local
